version: '2'

services:
  db:
    build: ./db/
    #image: mysql
    user: '1000:50'
    env_file:
      - ".env"
    ports:
      - 3306:3306
    volumes:
      - ./db/mysql/:/var/lib/mysql
    depends_on:
      - memcached
    container_name: db
  web:
    build: ./web
    restart: always
    env_file:
      - ".env"
    command:  bash -c  'sh DjangoBlog/bin/docker_start.sh'
    volumes:
      - ./web/codes:/code
    ports:
      - "8000:8000"
    links:
      - db
    depends_on:
      - db
    container_name: web

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes_from:
      - web
    links:
      - web:web
    container_name: nginx
  memcached:
    build: ./memcached/
    container_name: memcached
